import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Sidebar } from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[#1a1a1a] text-white min-h-screen flex items-center justify-center">
          <div className="max-w-4xl mx-auto p-8">
            <div className="flex gap-12">
              <div className="w-20"><Sidebar/></div>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
